### ISSUE TITLE
Change context in an Extension

### ISSUE THREAD

**Issue by eldersouza** [IssabelFoundation/issabel#27]
Why the context option is not visible in an Extension Configuration Page?

I created an extension and tried to change the context (I created some contexts in extensions_custom.conf), but I did not see this option listed. Then on the Extension page, I clicked on "- Device Options" to hide and click again to show these options. After that, the "context" option appears.

Thanks

**Comment by asternic** [comment]
Hi,

We are including the custom_contexts module (class of service) by default. This modules has an option to hide the context field because you can set it directly from the class of service option. As you find out, you can hide/show to make it visible again if you want to use your own extensions_custom conf contexts, anyways, consider looking/reading into the customcontext/class of service options that might work in your case and perhaps without the need to edit custom files.

If you want to change that behaviour, you can edit the file

/var/www/html/admin/modules/customcontexts/functions.inc.php

look for this line:

$js = '<script type="text/javascript">$(document).ready(function(){$("#devinfo_context").parent().parent().hide();});</script>';

and change it to:

$js='';

You can also uninstall the class of service/custom context module from IssabelPBX.

Best regards,
